accepted = [
	"Unlicense",
	"CC0-1.0",
	"ISC",
	"MIT",
	"MIT-0",
	"BSD-3-Clause",
	"Zlib",
	"Apache-2.0",
]

targets = ["wasm32-unknown-unnkown"]

no-clearly-defined = true

[unicode-ident]
accepted = ["Unicode-DFS-2016"]
