name: Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "build"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - uses: jetli/wasm-bindgen-action@v0.2.0
      - run: |
          cargo build --profile release-wasm --target wasm32-unknown-unknown
          wasm-bindgen --out-name maze --out-dir target/wasm --target web target/wasm32-unknown-unknown/release-wasm/maze.wasm
      - run: |
          mkdir web
          npx --package=binaryen -- wasm-opt -O4 --output web/maze_bg.wasm target/wasm/maze_bg.wasm
          cp target/wasm/maze.js web/maze.js
          cp index.html web/index.html
      - run: |
          cargo build --features console_log,debug --profile release --target wasm32-unknown-unknown
          wasm-bindgen --out-name maze --out-dir target/wasm --target web target/wasm32-unknown-unknown/release/maze_bg.wasm
      - run: |
          mkdir web/debug
          cp target/wasm/maze_bg.wasm web/debug/maze_bg.wasm
          cp target/wasm/maze.js web/debug/maze.js
          cp index.html web/debug/index.html
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./web
      - id: deployment
        uses: actions/deploy-pages@v1
