name: Build and Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "build"
  cancel-in-progress: false

jobs:
  licenses:
    name: Gather and Publish License Info
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "github-actions@users.noreply.github.com"
          git tag ${{ github.event.head_commit.timestamp }}
          git push origin ${{ github.event.head_commit.timestamp }}
      - run: |
          cargo install --locked cargo-about
          cargo about generate -o ATTRIBUTION.html --all-features about.hbs
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.head_commit.timestamp }}
          fail_on_unmatched_files: true
          files: ATTRIBUTION.html

  release:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
    name: Build and Release - Linux
    needs: licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: |
          sudo apt update
          sudo apt install -y musl-tools musl-dev crossbuild-essential-arm64
          cargo build --release --target ${{ matrix.target }}
          mv target/${{ matrix.target }}/release/maze labirynt-${{ matrix.target }}
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.head_commit.timestamp }}
          fail_on_unmatched_files: true
          files: labirynt-${{ matrix.target }}

  release-windows:
    strategy:
      fail-fast: false
      matrix:
        target:
          - x86_64-pc-windows-msvc
    name: Build and Release - Windows
    needs: licenses
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
      - run: |
          cargo build --release --target ${{ matrix.target }}
          cp "target/${{ matrix.target }}/release/maze.exe" "labirynt-${{ matrix.target }}.exe"
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.head_commit.timestamp }}
          fail_on_unmatched_files: true
          files: labirynt-${{ matrix.target }}.exe

  release-web:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Build and Release - Web
    needs: licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/configure-pages@v2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - uses: jetli/wasm-bindgen-action@v0.2.0
      - run: |
          cargo build --profile release-wasm --target wasm32-unknown-unknown
          wasm-bindgen --out-name maze --out-dir target/wasm --target web target/wasm32-unknown-unknown/release-wasm/maze.wasm
      - run: |
          mkdir web
          npx --package=binaryen -- wasm-opt -O4 --output web/maze_bg.wasm target/wasm/maze_bg.wasm
          cp target/wasm/maze.js web/maze.js
          cp index.html web/index.html
      - run: |
          cargo build --features console_log,debug --profile release --target wasm32-unknown-unknown
          wasm-bindgen --out-name maze --out-dir target/wasm --target web target/wasm32-unknown-unknown/release/maze.wasm
      - run: |
          mkdir web/debug
          cp target/wasm/maze_bg.wasm web/debug/maze_bg.wasm
          cp target/wasm/maze.js web/debug/maze.js
          cp index.html web/debug/index.html
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./web
      - id: deployment
        uses: actions/deploy-pages@v1
      - run: tar -czvf labirynt-web.tar.gz web
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.event.head_commit.timestamp }}
          fail_on_unmatched_files: true
          files: labirynt-web.tar.gz
          body: Również dostępne na [https://j-markiewicz.github.io/maze](https://j-markiewicz.github.io/maze)([/debug](https://j-markiewicz.github.io/maze/debug)).
