name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        features: ["default", "debug", "console_log", "debug,console_log"]
        target: ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo check --target ${{ matrix.target }} --features ${{ matrix.features }}

  fmt:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt
          targets: wasm32-unknown-unknown
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly fmt --all -- --check

  clippy:
    strategy:
      matrix:
        features: ["default", "debug", "console_log", "debug,console_log"]
        target: ["x86_64-unknown-linux-gnu", "wasm32-unknown-unknown"]
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: clippy
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo +nightly clippy --profile release-wasm --target ${{ matrix.target }} --features ${{ matrix.features }} -- --D warnings
